"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import registry from "./plugins.json";
import { pluginSlug } from "./plugin-utils";

type Plugin=(typeof registry.plugins)[number];
const SIZE=12, icons:Record<string,string>={ui:"◫",session:"◎",tools:"⌘",workflow:"↗",notify:"◉",dev:"⚙",fun:"✦"}, tones=["violet","cyan","amber","rose","lime","blue","orange"];
const text={
 en:{subtitle:"DeepSeek Harness plugin marketplace",search:"Search plugins, capabilities or authors…",dev:"Developer center",submit:"Submit plugin",browse:"Browse",discover:"Discover all",pick:"Editor’s pick",github:"GitHub repository",cats:"Categories",build:"Build your first plugin",buildDesc:"Declare dsh.bundle and join the Harness plugin ecosystem.",template:"View plugin template →",market:"Plugin marketplace",directory:"Community directory",updated:"Updated",headline:"DeepSeek Harness plugins for every workflow",intro:"Discover community-built DeepSeek Harness plugins for interfaces, tools, memory, integrations and automation—complete with source links and ready-to-run install commands.",available:"community plugins ready to explore",starter:"BEST FOR NEW USERS",curated:"Community curated · by",included:"Listed in DSH Market",copy:"Copy install command",copied:"Install command copied ✓",details:"View plugin details →",all:"All plugins",found:"plugins found · sourced from the community-maintained registry",allCats:"All categories",newest:"Recently added",alpha:"Name A–Z",publisher:"Community publisher",added:"Added",copyShort:"Copy install",copiedShort:"Copied ✓",empty:"No matching plugins",emptyDesc:"Try a shorter search term or choose another category.",clear:"Clear filters",showing:"Showing",of:"of",safety:"Review source code and permissions before installing third-party code.",source:"Data source ↗"},
 zh:{subtitle:"DeepSeek Harness 插件市场",search:"搜索插件、能力或作者…",dev:"开发者中心",submit:"提交插件",browse:"浏览",discover:"发现全部",pick:"编辑精选",github:"GitHub 仓库",cats:"分类",build:"构建你的第一个插件",buildDesc:"声明 dsh.bundle，即可加入 Harness 插件生态。",template:"查看插件模板 →",market:"插件市场",directory:"社区目录",updated:"更新于",available:"个社区插件可供探索",starter:"新用户首选",curated:"社区策展 · by",included:"已收录于 Awesome DSH Plugin",copy:"复制安装命令",copied:"安装命令已复制 ✓",details:"查看插件详情 →",all:"全部插件",found:"个插件，数据来自社区维护的公开目录",allCats:"全部分类",newest:"最近收录",alpha:"名称排序",publisher:"社区发布者",added:"收录日期",copyShort:"复制安装",copiedShort:"已复制 ✓",empty:"没有找到匹配插件",emptyDesc:"尝试更短的关键词，或切换到其他分类。",clear:"清除筛选",showing:"显示",of:"共",safety:"安装第三方代码前，请审阅源代码及权限。",source:"数据源 ↗"}
};

function initials(name:string){return name.replace(/^@[^/]+\//,"").replace(/^dsh[-_]?/i,"").split(/[-_]/).filter(Boolean).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"DS"}

export default function Marketplace({locale}:{locale:"en"|"zh"}){
 const t=text[locale],prefix=locale==="zh"?"/zh":"";
 const [query,setQuery]=useState(""),[category,setCategory]=useState("all"),[sort,setSort]=useState<"new"|"name">("new"),[page,setPage]=useState(1),[copied,setCopied]=useState<string|null>(null); const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}};addEventListener("keydown",h);return()=>removeEventListener("keydown",h)},[]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(registry.categories).map(k=>[k,registry.plugins.filter(p=>p.category===k).length])),[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return registry.plugins.filter(p=>(category==="all"||p.category===category)&&(!q||`${p.name} ${p.owner} ${p.description.zh} ${p.description.en}`.toLowerCase().includes(q))).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):b.added.localeCompare(a.added))},[query,category,sort]);
 const pages=Math.max(1,Math.ceil(filtered.length/SIZE)),visible=filtered.slice((page-1)*SIZE,page*SIZE); useEffect(()=>setPage(1),[query,category,sort]);
 async function copy(p:Plugin){await navigator.clipboard.writeText(p.install);setCopied(p.name);setTimeout(()=>setCopied(null),1600)}
 function choose(v:string){setCategory(v);document.getElementById("plugin-list")?.scrollIntoView({behavior:"smooth"})}
 return <div className="shell"><header className="topbar"><a className="brand" href="#top"><span className="mark">DS</span><span><strong>DSH Market</strong><small>{t.subtitle}</small></span></a><label className="search"><i>⌕</i><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} aria-label={t.search} placeholder={t.search}/><kbd>⌘ K</kbd></label><div className="top-actions"><div className="lang-switch"><a className={locale==="en"?"on":""} href="/">EN</a><a className={locale==="zh"?"on":""} href="/zh/">中文</a></div><a className="ghost" href="https://github.com/tjsdyy/dshplugin#development" target="_blank">{t.dev}</a><a className="primary" href="https://github.com/tjsdyy/dshplugin/issues/new?labels=plugin-submission" target="_blank">{t.submit}</a></div></header>
 <div className="body" id="top"><aside><p className="side-label">{t.browse}</p><nav className="nav"><button className={category==="all"?"active":""} onClick={()=>choose("all")}><span className="ico">⌂</span><span>{t.discover}</span><small>{registry.count}</small></button><a href={registry.source} target="_blank"><span className="ico">↗</span><span>{t.github}</span></a></nav><p className="side-label">{t.cats}</p><nav className="nav">{Object.entries(registry.categories).map(([k,l])=><button key={k} className={category===k?"active":""} onClick={()=>choose(k)}><span className="ico">{icons[k]}</span><span>{l[locale]}</span><small>{counts[k]}</small></button>)}</nav><div className="side-note"><strong>{t.build}</strong><p>{t.buildDesc}</p><a href="https://github.com/tjsdyy/dshplugin#development" target="_blank">{t.template}</a></div></aside>
 <main><div className="crumb">{t.market} <span>/</span> {t.directory}<b>{t.updated} {registry.updated}</b></div>
 <section id="plugin-list" className="listing listing-first"><div className="toolbar"><div className="section-title"><h1>{category==="all"?(locale==="en"?"DeepSeek Harness Plugin Directory":"DeepSeek Harness 插件目录"):registry.categories[category as keyof typeof registry.categories][locale]}</h1><p>{filtered.length} {t.found}</p></div><div className="filters"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">{t.allCats}</option>{Object.entries(registry.categories).map(([k,l])=><option value={k} key={k}>{l[locale]}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as "new"|"name")}><option value="new">{t.newest}</option><option value="name">{t.alpha}</option></select></div></div>
 {visible.length?<div className="list">{visible.map((p,i)=><article className="plugin" key={p.name}><div className={`picon ${tones[(i+page)%tones.length]}`}>{initials(p.name)}</div><div className="plugin-main"><a className="pname" href={`${prefix}/plugin/${pluginSlug(p.name)}`}>{p.name}<span>→</span></a><div className="pdesc">{p.description[locale]}</div></div><div className="author"><b>{p.owner}</b>{t.publisher}</div><div><button className="tag" onClick={()=>choose(p.category)}>{registry.categories[p.category as keyof typeof registry.categories][locale]}</button></div><div className="date"><b>{p.added}</b>{t.added}</div><button className={`get ${copied===p.name?"done":""}`} onClick={()=>copy(p)}>{copied===p.name?t.copiedShort:t.copyShort}</button></article>)}</div>:<div className="empty"><b>⌕</b><h3>{t.empty}</h3><p>{t.emptyDesc}</p><button onClick={()=>{setQuery("");setCategory("all")}}>{t.clear}</button></div>}
 <div className="footerline"><span>{t.showing} {filtered.length?(page-1)*SIZE+1:0}–{Math.min(page*SIZE,filtered.length)} · {t.of} {filtered.length}</span><div className="pages"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>‹</button>{Array.from({length:Math.min(5,pages)},(_,i)=>{const start=Math.min(Math.max(1,page-2),Math.max(1,pages-4)),n=start+i;return <button key={n} className={n===page?"on":""} onClick={()=>setPage(n)}>{n}</button>})}<button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>›</button></div></div></section>
 <div className="knowledge-hub">
  <section className="seo-section overview-section"><div className="seo-heading"><span>DEEPSEEK HARNESS PLUGIN GUIDE</span><h2>{locale==="en"?"What is a DeepSeek Harness plugin?":"什么是 DeepSeek Harness Plugin？"}</h2><p>{locale==="en"?`A DeepSeek Harness plugin is an installable bundle that changes or extends how the agent works. Plugins can add tools, user interfaces, memory, model providers, sandboxes, integrations, session storage and automation. DSH Market is a searchable directory of ${registry.count} community plugins with source links and ready-to-run installation commands.`:`DeepSeek Harness Plugin 是改变或扩展 Agent 工作方式的可安装扩展包，可增加工具、用户界面、记忆、模型供应商、沙箱、集成、会话存储与自动化能力。DSH Market 收录 ${registry.count} 个社区插件，并提供源码和可直接运行的安装命令。`}</p></div><div className="principle-grid">{(locale==="en"?[{n:"01",h:"Discover",p:"Search by plugin name, capability, category or maintainer."},{n:"02",h:"Review",p:"Read the description, repository source, dependencies and permissions."},{n:"03",h:"Install",p:"Run the plugin’s dsh plugin --profile web add command."},{n:"04",h:"Compose",p:"Combine plugins into a Harness profile for your workflow."}]:[{n:"01",h:"发现",p:"按插件名称、能力、分类或维护者搜索。"},{n:"02",h:"审阅",p:"检查介绍、源码仓库、依赖和权限。"},{n:"03",h:"安装",p:"运行插件提供的 dsh plugin --profile web add 命令。"},{n:"04",h:"组合",p:"将多个插件组合成适合工作流的 Harness Profile。"}]).map(x=><div key={x.n}><b>{x.n}</b><h3>{x.h}</h3><p>{x.p}</p></div>)}</div></section>
  <section className="knowledge-section"><div className="knowledge-title"><span>HOW IT WORKS</span><h2>{locale==="en"?"How the plugin system works":"插件系统的工作原理"}</h2></div><div className="prose-columns"><p>{locale==="en"?"DeepSeek Harness is built around composable bundles. A plugin declares a dsh.bundle manifest that tells the harness which modules, tools, UI patches or runtime components to load. Profiles determine which set of plugins is active for a specific agent experience.":"DeepSeek Harness 以可组合 Bundle 为核心。插件通过 dsh.bundle 清单告诉 Harness 要加载哪些模块、工具、界面补丁或运行时组件；Profile 决定特定 Agent 体验启用哪些插件。"}</p><p>{locale==="en"?"The installation command records the plugin in a target profile. After loading, the plugin participates only through the extension points it declares. Because plugins may execute code locally, source review and least-privilege configuration are important before activation.":"安装命令会把插件记录到目标 Profile。加载后，插件只通过其声明的扩展点参与运行。由于插件可能在本机执行代码，启用前应审阅源码并遵循最小权限原则。"}</p></div></section>
  <section className="knowledge-section"><div className="knowledge-title"><span>CAPABILITIES</span><h2>{locale==="en"?"Common DeepSeek Harness plugin types":"常见 DeepSeek Harness 插件类型"}</h2></div><div className="term-grid">{Object.entries(registry.categories).map(([key,label])=>{const descriptions:Record<string,{en:string,zh:string}>={ui:{en:"Composer, sidebar, navigation and visual interaction enhancements.",zh:"输入框、侧边栏、导航和可视化交互增强。"},session:{en:"Conversation history, memory, sharing and cross-session context.",zh:"会话历史、记忆、分享和跨会话上下文。"},tools:{en:"New agent actions for data, files, browsers, code and external systems.",zh:"面向数据、文件、浏览器、代码和外部系统的新操作能力。"},workflow:{en:"Scheduling, orchestration, research loops and multi-agent automation.",zh:"定时任务、编排、研究循环和多 Agent 自动化。"},notify:{en:"Messaging, alerts and bridges to communication platforms.",zh:"消息通知、提醒以及通信平台桥接。"},dev:{en:"Models, sandboxes, observability, security and runtime infrastructure.",zh:"模型、沙箱、可观测性、安全与运行时基础设施。"},fun:{en:"Games, reactions and playful experiences while agents work.",zh:"Agent 工作期间的游戏、互动和趣味体验。"}};return <div key={key}><b>{icons[key]} {label[locale]}</b><p>{descriptions[key][locale]}</p></div>})}</div></section>
  <section className="knowledge-section"><div className="knowledge-title"><span>GLOSSARY</span><h2>{locale==="en"?"DeepSeek Harness terminology":"DeepSeek Harness 常见名词"}</h2></div><dl className="glossary-grid">{(locale==="en"?[["DSH","The command-line name commonly used for DeepSeek Harness."],["Plugin","An installable bundle that extends or replaces harness behavior."],["Bundle manifest","The dsh.bundle declaration describing a plugin’s entry points."],["Profile","A named configuration that selects plugins for an agent experience."],["Tool","A callable capability exposed to the model, such as search or file access."],["Harness","The runtime that connects models, tools, sessions, UI and the agent loop."]]:[["DSH","DeepSeek Harness 常用的命令行简称。"],["Plugin","扩展或替换 Harness 行为的可安装 Bundle。"],["Bundle manifest","描述插件入口点的 dsh.bundle 清单。"],["Profile","为特定 Agent 体验选择插件的命名配置。"],["Tool","提供给模型调用的能力，例如搜索或文件访问。"],["Harness","连接模型、工具、会话、界面与 Agent Loop 的运行框架。"]]).map(([term,desc])=><div key={term}><dt>{term}</dt><dd>{desc}</dd></div>)}</dl></section>
  <section className="knowledge-section faq-section"><div className="knowledge-title"><span>FAQ</span><h2>{locale==="en"?"DeepSeek Harness plugin FAQ":"DeepSeek Harness Plugin 常见问题"}</h2></div><div className="faq-grid">{(locale==="en"?[{q:"Where can I find DeepSeek Harness plugins?",a:`DSH Market organizes ${registry.count} community plugins across UI, Sessions, Tools, Automation, Integrations, Runtime and Fun.`},{q:"How do I install a DSH plugin?",a:"Open its detail page, review the source, then copy and run the provided dsh plugin --profile web add command."},{q:"What is a DSH profile?",a:"A profile is a named plugin configuration. The web profile controls plugins loaded for the Harness web experience."},{q:"Can plugins change the agent loop?",a:"Yes. DeepSeek Harness exposes many core parts as plugin extension points, including tools, UI, storage, models and agent behavior."},{q:"Can I use several plugins together?",a:"Yes. Plugins are designed to be composed in a profile, although you should check compatibility and overlapping patches."},{q:"Are community plugins safe?",a:"Listing is not a security endorsement. Review source, dependencies, permissions and maintenance status before installation."},{q:"How do I create a plugin?",a:"Start with a plugin template, implement the extension points you need and declare them through a dsh.bundle manifest."},{q:"How is this directory maintained?",a:"The registry is community curated. Each entry records a repository, author, category, description, install command and added date."}]:[{q:"在哪里查找 DeepSeek Harness 插件？",a:`DSH Market 收录 ${registry.count} 个社区插件，覆盖 UI、会话、工具、自动化、集成、运行时和娱乐。`},{q:"如何安装 DSH 插件？",a:"进入详情页审阅源码，然后复制并运行页面提供的 dsh plugin --profile web add 命令。"},{q:"什么是 DSH Profile？",a:"Profile 是命名的插件配置；web Profile 控制 Harness Web 体验加载哪些插件。"},{q:"插件可以改变 Agent Loop 吗？",a:"可以。DeepSeek Harness 将工具、UI、存储、模型和 Agent 行为等核心部分开放为插件扩展点。"},{q:"可以组合多个插件吗？",a:"可以。插件可在同一 Profile 中组合，但应检查兼容性以及是否存在重复补丁。"},{q:"社区插件安全吗？",a:"收录不等于安全背书。安装前请审阅源码、依赖、权限和维护状态。"},{q:"如何开发插件？",a:"从插件模板开始，实现所需扩展点，并通过 dsh.bundle 清单进行声明。"},{q:"这个目录如何维护？",a:"目录由社区策展，每个条目记录仓库、作者、分类、介绍、安装命令和收录日期。"}]).map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></section>
 </div>
 <footer><span>DSH Market</span><p>{t.safety}</p><a href={registry.source} target="_blank">{t.source}</a></footer></main></div></div>
}
