"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import registry from "./plugins.json";
import { pluginSlug } from "./plugin-utils";

type Plugin=(typeof registry.plugins)[number];
const SIZE=12, icons:Record<string,string>={ui:"◫",session:"◎",tools:"⌘",workflow:"↗",notify:"◉",dev:"⚙",fun:"✦"}, tones=["violet","cyan","amber","rose","lime","blue","orange"];
const text={
 en:{subtitle:"DeepSeek Harness plugin marketplace",search:"Search plugins, capabilities or authors…",dev:"Developer center",submit:"Submit plugin",browse:"Browse",discover:"Discover all",pick:"Editor’s pick",github:"GitHub repository",cats:"Categories",build:"Build your first plugin",buildDesc:"Declare dsh.bundle and join the Harness plugin ecosystem.",template:"View plugin template →",market:"Plugin marketplace",directory:"Community directory",updated:"Updated",headline:"Extend every Harness capability",intro:"Community-built interfaces, tools, memory and automation workflows that move DeepSeek Harness from conversation to execution.",available:"community plugins ready to explore",starter:"BEST FOR NEW USERS",curated:"Community curated · by",included:"Listed in Awesome DSH Plugin",copy:"Copy install command",copied:"Install command copied ✓",details:"View plugin details →",all:"All plugins",found:"plugins found · sourced from the community-maintained registry",allCats:"All categories",newest:"Recently added",alpha:"Name A–Z",publisher:"Community publisher",added:"Added",copyShort:"Copy install",copiedShort:"Copied ✓",empty:"No matching plugins",emptyDesc:"Try a shorter search term or choose another category.",clear:"Clear filters",showing:"Showing",of:"of",safety:"Review source code and permissions before installing third-party code.",source:"Data source ↗"},
 zh:{subtitle:"DeepSeek Harness 插件市场",search:"搜索插件、能力或作者…",dev:"开发者中心",submit:"提交插件",browse:"浏览",discover:"发现全部",pick:"编辑精选",github:"GitHub 仓库",cats:"分类",build:"构建你的第一个插件",buildDesc:"声明 dsh.bundle，即可加入 Harness 插件生态。",template:"查看插件模板 →",market:"插件市场",directory:"社区目录",updated:"更新于",headline:"为 Harness 扩展每一种能力",intro:"来自社区的界面、工具、记忆与自动化工作流，让 DeepSeek Harness 从对话走向真实执行。",available:"个社区插件可供探索",starter:"新用户首选",curated:"社区策展 · by",included:"已收录于 Awesome DSH Plugin",copy:"复制安装命令",copied:"安装命令已复制 ✓",details:"查看插件详情 →",all:"全部插件",found:"个插件，数据来自社区维护的公开目录",allCats:"全部分类",newest:"最近收录",alpha:"名称排序",publisher:"社区发布者",added:"收录日期",copyShort:"复制安装",copiedShort:"已复制 ✓",empty:"没有找到匹配插件",emptyDesc:"尝试更短的关键词，或切换到其他分类。",clear:"清除筛选",showing:"显示",of:"共",safety:"安装第三方代码前，请审阅源代码及权限。",source:"数据源 ↗"}
};

function initials(name:string){return name.replace(/^@[^/]+\//,"").replace(/^dsh[-_]?/i,"").split(/[-_]/).filter(Boolean).map(x=>x[0]).join("").slice(0,2).toUpperCase()||"DS"}

export default function Marketplace({locale}:{locale:"en"|"zh"}){
 const t=text[locale],prefix=locale==="zh"?"/zh":"";
 const [query,setQuery]=useState(""),[category,setCategory]=useState("all"),[sort,setSort]=useState<"new"|"name">("new"),[page,setPage]=useState(1),[copied,setCopied]=useState<string|null>(null); const searchRef=useRef<HTMLInputElement>(null);
 const featured=registry.plugins.find(p=>p.name==="dsh-find-plugin")!;
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}};addEventListener("keydown",h);return()=>removeEventListener("keydown",h)},[]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(registry.categories).map(k=>[k,registry.plugins.filter(p=>p.category===k).length])),[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return registry.plugins.filter(p=>(category==="all"||p.category===category)&&(!q||`${p.name} ${p.owner} ${p.description.zh} ${p.description.en}`.toLowerCase().includes(q))).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):b.added.localeCompare(a.added))},[query,category,sort]);
 const pages=Math.max(1,Math.ceil(filtered.length/SIZE)),visible=filtered.slice((page-1)*SIZE,page*SIZE); useEffect(()=>setPage(1),[query,category,sort]);
 async function copy(p:Plugin){await navigator.clipboard.writeText(p.install);setCopied(p.name);setTimeout(()=>setCopied(null),1600)}
 function choose(v:string){setCategory(v);document.getElementById("plugin-list")?.scrollIntoView({behavior:"smooth"})}
 return <div className="shell"><header className="topbar"><a className="brand" href="#top"><span className="mark">DS</span><span><strong>DSH Market</strong><small>{t.subtitle}</small></span></a><label className="search"><i>⌕</i><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} aria-label={t.search} placeholder={t.search}/><kbd>⌘ K</kbd></label><div className="top-actions"><div className="lang-switch"><a className={locale==="en"?"on":""} href="/">EN</a><a className={locale==="zh"?"on":""} href="/zh/">中文</a></div><a className="ghost" href="https://github.com/tjsdyy/dshplugin#development" target="_blank">{t.dev}</a><a className="primary" href="https://github.com/tjsdyy/dshplugin/issues/new?labels=plugin-submission" target="_blank">{t.submit}</a></div></header>
 <div className="body" id="top"><aside><p className="side-label">{t.browse}</p><nav className="nav"><button className={category==="all"?"active":""} onClick={()=>choose("all")}><span className="ico">⌂</span><span>{t.discover}</span><small>{registry.count}</small></button><a href="#featured"><span className="ico">✦</span><span>{t.pick}</span></a><a href={registry.source} target="_blank"><span className="ico">↗</span><span>{t.github}</span></a></nav><p className="side-label">{t.cats}</p><nav className="nav">{Object.entries(registry.categories).map(([k,l])=><button key={k} className={category===k?"active":""} onClick={()=>choose(k)}><span className="ico">{icons[k]}</span><span>{l[locale]}</span><small>{counts[k]}</small></button>)}</nav><div className="side-note"><strong>{t.build}</strong><p>{t.buildDesc}</p><a href="https://github.com/tjsdyy/dshplugin#development" target="_blank">{t.template}</a></div></aside>
 <main><div className="crumb">{t.market} <span>/</span> {t.directory}<b>{t.updated} {registry.updated}</b></div><section className="intro"><div><h1>{t.headline}</h1><p>{t.intro}</p></div><div className="status"><span className="pulse"/>{registry.count} {t.available}</div></section>
 <section className="featured" id="featured"><div className="feature-copy"><div className="eyebrow">{t.starter}</div><div className="feature-title"><div className="plugin-logo">FP</div><div><h2>{featured.name}</h2><span className="verified">● {t.curated} {featured.owner}</span></div></div><p>{featured.description[locale]}</p><div className="chips"><span className="chip">Plugin search</span><span className="chip">Discovery</span><span className="chip">Install command</span><span className="chip">Community</span></div></div><div className="feature-meta"><div className="rating"><span className="verified-dot">✓</span>{t.included}</div><button className="install" onClick={()=>copy(featured)}>{copied===featured.name?t.copied:t.copy}</button><div className="install-code">{featured.install}</div><a href={`${prefix}/plugin/${pluginSlug(featured.name)}`}>{t.details}</a></div></section>
 <section id="plugin-list" className="listing"><div className="toolbar"><div className="section-title"><h2>{category==="all"?t.all:registry.categories[category as keyof typeof registry.categories][locale]}</h2><p>{filtered.length} {t.found}</p></div><div className="filters"><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">{t.allCats}</option>{Object.entries(registry.categories).map(([k,l])=><option value={k} key={k}>{l[locale]}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as "new"|"name")}><option value="new">{t.newest}</option><option value="name">{t.alpha}</option></select></div></div>
 {visible.length?<div className="list">{visible.map((p,i)=><article className="plugin" key={p.name}><div className={`picon ${tones[(i+page)%tones.length]}`}>{initials(p.name)}</div><div className="plugin-main"><a className="pname" href={`${prefix}/plugin/${pluginSlug(p.name)}`}>{p.name}<span>→</span></a><div className="pdesc">{p.description[locale]}</div></div><div className="author"><b>{p.owner}</b>{t.publisher}</div><div><button className="tag" onClick={()=>choose(p.category)}>{registry.categories[p.category as keyof typeof registry.categories][locale]}</button></div><div className="date"><b>{p.added}</b>{t.added}</div><button className={`get ${copied===p.name?"done":""}`} onClick={()=>copy(p)}>{copied===p.name?t.copiedShort:t.copyShort}</button></article>)}</div>:<div className="empty"><b>⌕</b><h3>{t.empty}</h3><p>{t.emptyDesc}</p><button onClick={()=>{setQuery("");setCategory("all")}}>{t.clear}</button></div>}
 <div className="footerline"><span>{t.showing} {filtered.length?(page-1)*SIZE+1:0}–{Math.min(page*SIZE,filtered.length)} · {t.of} {filtered.length}</span><div className="pages"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>‹</button>{Array.from({length:Math.min(5,pages)},(_,i)=>{const start=Math.min(Math.max(1,page-2),Math.max(1,pages-4)),n=start+i;return <button key={n} className={n===page?"on":""} onClick={()=>setPage(n)}>{n}</button>})}<button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>›</button></div></div></section><footer><span>Awesome DSH Plugin</span><p>{t.safety}</p><a href={registry.source} target="_blank">{t.source}</a></footer></main></div></div>
}
